# Generated by Django 4.2.2 on 2023-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('numero_puertas', models.IntegerField()),
                ('numero_asientos', models.IntegerField()),
                ('trasmision', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
